### ISSUE TITLE
sway, wlroots IME 현황

### ISSUE THREAD

**Issue by simnalamburt** [korean-input/issues#7]
> [한국어로 보기](#korean)

&nbsp;

## Environment
* Operating System: Linux
* Software version: sway 1.5.1, wlroots 0.12.0

## Summary
Despite the fact the sway is the one of the most used wayland compositor, it currently lacks the implementation of keyboard grab feature of input-method-unstable-v2 protocol. A PR for this issue, [swaywm/sway#4932] was submitted but it's not merged due to several bugs. We must fix the bugs and support input methods to the sway.

[This][sway-im] is the build of sway with [swaywm/sway#4932] being merged.

## Current bugs
First you must install sway 1.5.1, wlroots 0.12.0 and setup the Korean IME with input-method-unstable-v2 support. There bugs are reproducible with [kime] and [fcitx5].

### 1. ~~Key repeat bug~~ &rarr; Bug of both [kime] and [fcitx5], fixed in [kime]
<strike>
This bug is not related with key repeat feature of IME. For example, this bug is reproducible with IMEs which lacks the key repeat feature like old version of kime without or wlhangul. Sway's input-method-unstable-v2 implementation of wlroots is the suspected cause.

- Error reproduction steps 1: Hold <kbd>Alt</kbd> for 3 seconds → Press <kbd>1</kbd> → Immediately release <kbd>Alt</kbd> and <kbd>1</kbd>
  - Expected behavior: <kbd>Alt</kbd> + <kbd>1</kbd> is typed once
  - Actual behavior: <kbd>1</kbd> is typed infinitely
- Error reproduction steps 2: Hold <kbd>Ctrl</kbd> for 3 seconds → Press <kbd>Tab</kbd> → Immediately release <kbd>Ctrl</kbd> and <kbd>Tab</kbd>
  - Expected behavior: <kbd>Ctrl</kbd> + <kbd>Tab</kbd> is typed once
  - Actual behavior: <kbd>Tab</kbd> is typed infinitely
- Error reproduction steps 2: Hold <kbd>a</kbd> for 3 seconds → Press <kbd>b</kbd> → Immediately release <kbd>a</kbd> and <kbd>b</kbd>
  - Expected behavior: Repeat of <kbd>a</kbd> stops as soon as user release <kbd>a</kbd> and <kbd>b</kbd>
  - Actual behavior: <kbd>b</kbd> is typed infinitely
</strike>

### 2. Focus change bug
I think it's caused by the timing of wlroots' deactivate, done event. But not sure though.

**Update**: This bug in inevitable with input-method-unstable-v2 protocol. See https://github.com/swaywm/sway/pull/4932#issuecomment-774113129. Only possible workaround is to discard preedit strings on deactivate event.

- Error reproduction steps:
  1. Create two alacritty instance. Make sure that they use the wayland backend.
  2. In A terminal, type "한[글]". ("글" means string which is still in preedit mode)
  3. Change the focus to the B terminal
- Expected behavior: "한글" in terminal A, nothing in B
- Actual behavior: "한" in A, "글" in B

## References
- https://github.com/swaywm/sway/pull/4932

&nbsp;

--------

<p name="korean">(korean translation)</p>

## 환경
* 운영채제: Linux
* 버전: sway 1.5.1, wlroots 0.12.0

## 요약
sway는 굉장히 메이저하게 쓰이는 wayland compositier중 하나임에도, 다국어입력기 사용을 위해 필수적인 keyboard grab 프로토콜이 아직 구현되어있지 않았습니다. 이를 위한 PR인 [swaywm/sway#4932]가 현재 submit된 상태인데, 버그가 있어 아직 머지되지 못하고있습니다. [swaywm/sway#4932]의 버그를 마저 고치고, sway에 다국어 지원을 넣어야만 합니다.

[swaywm/sway#4932]가 머지된 버전의 sway는 [여기][sway-im]에서 받아볼 수 있습니다.

## 현재 버그
먼저 sway 1.5.1, wlroots 0.12.0를 설치한 뒤, input-method-unstable-v2 프로토콜을 지원하는 한글 입력기를 설치한다. [kime]와 [fcitx5] 에서 재현 가능하다.

### 1. ~~키 반복 버그~~ &rarr; [kime]와 [fcitx5]의 버그였음, [kime]에선 고쳐짐
<strike>
이 키 반복 버그 자체는 IME의 키 반복 기능과는 상관없이 발생합니다. 예를들어 키 반복기능이 없는 구버전 kime나 wlhangul을 사용해도 재현이 가능하기 때문입니다. sway의 input-method-unstable-v2 구현이나 wlroots 구현 문제인것으로 생각됩니다.

- 재현 방법 1: <kbd>Alt</kbd> 누름 → 3초 유지 → <kbd>1</kbd> 누름 → 즉시 <kbd>Alt</kbd>, <kbd>1</kbd> 동시에 뗌
  - 원하는 동작: <kbd>Alt</kbd> + <kbd>1</kbd>이 1회 입력됨
  - 실제 동작: <kbd>1</kbd>이 무한으로 입력됨
- 재현 방법 2: <kbd>Ctrl</kbd> 누름 → 3초 유지 → <kbd>Tab</kbd> 누름 → 즉시 <kbd>Ctrl</kbd>, <kbd>Tab</kbd> 동시에 뗌
  - 원하는 동작: <kbd>Ctrl</kbd> + <kbd>Tab</kbd>이 1회 입력됨
  - 실제 동작: <kbd>Tab</kbd>이 무한으로 입력됨
- 재현 방법 2: <kbd>a</kbd> 누름 → 3초 유지 → <kbd>b</kbd> 누름 → 즉시 <kbd>a</kbd>, <kbd>b</kbd> 동시에 뗌
  - 원하는 동작: <kbd>a</kbd>, <kbd>b</kbd>를 떼는 순간 입력이 멈춤
  - 실제 동작: <kbd>b</kbd>가 무한으로 입력됨
</strike>

### 2. 포커스 변환 버그
wlroots가 IME에 deactivate, done 이벤트를 주는 타이밍의 문제인것으로 생각되는데, 확실치는 않습니다.

**업데이트**: 이 버그는 input-method-unstable-v2 프로토콜을 쓰는 이상 피할 수 없다. https://github.com/swaywm/sway/pull/4932#issuecomment-774113129 참고. 유일한 우회책은 deactivate event가 들어오면 preedit 문자열을 버리는 것이다.

- 재현 방법:
  1. wayland를 써서 두 alacritty 터미널를 켬
  2. A 터미널에서 "한[글]" 까지 입력함 ("글"은 아직 preedit인 상태)
  3. B 터미널로 포커스를 옮김
- 원하는 동작: A에 "한글"이 완성됨, B에 아무것도 입력되지 않음
- 실제 동작: A에 "한"까지 입력됨, B에 "글"이 입력됨

## 참고자료
- https://github.com/swaywm/sway/pull/4932

CC @guswns0528

[swaywm/sway#4932]: https://github.com/swaywm/sway/pull/4932
[sway-im]: https://github.com/simnalamburt/PKGBUILD/tree/main/sway-im
[kime]: https://github.com/Riey/kime
[fcitx5]: https://github.com/fcitx/fcitx5/
[wlhangul]: https://github.com/emersion/wlhangul

**Comment by Riey** [comment]
sway 1.6이 릴리즈 되었습니다.

https://github.com/swaywm/sway/releases/tag/1.6
